---
- name: Deploy fapolicyd
  hosts: localhost
  become: yes
  vars:
    rules:
      - decision: allow
        perm: execute
        subject: exe/usr/bin/bash trust=1
        object: dir=/opt/splunk/bin/ all trust=0
      - decision: allow
        perm: open
        subject: exe=/usr/bin/bash trust=1
        object: dir=/opt/splunk/lib/ all trust=0
      - decision: allow
        perm: open
        subject: exe=/opt/splunk
        object: ftype=text/x-python trust=1
      - decision: allow
        perm: open
        subject: exe=/opt/splunk/bin/python3.7
        object: ftype=text/x-python trust=1
        
  roles:
    - fapolicyd_role #This role deploys the fapolicyd (application control) capability
