---
# tasks file for roles/aide

- name: Install aide
  ansible.builtin.dnf:
    name: "{{ aide_pkg }}"
    state: present

- name: Ensure aide directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop:
    - "{{ aide_logdir }}"
    - "{{ aide_dbdir }}"

# Use shell here so it gets full environment
- name: Capture aide binary path
  ansible.builtin.shell: which aide
  register: aide_path
  changed_when: no
  check_mode: no

- name: Check for existing AIDE database
  ansible.builtin.stat:
    path: "{{ aide_dbdir }}/{{ aide_database_filename }}"
  register: aide_db_check
  changed_when: not aide_db_check.stat.exists
  notify:
    - Initialise aide database
    - Move new aide database into place

- name: Configure aide
  ansible.builtin.template:
    src: aide.conf.j2
    dest: "{{ aide_conf_path }}"
    validate: "{{ aide_path.stdout }} -D -c %s"

- name: Update aide database
  ansible.builtin.command: "{{ aide_path.stdout }} -u"
  register: aide_update
  failed_when: aide_update.rc > 7
  when:
    - aide_db_check.stat.exists
    - aide_update_db == true
  notify:
    - Move new aide database into place
      
